#!/usr/bin/env python3
"""Preprocess a daily AI digest markdown file for nicer Apple Notes display.

The source `daily/*.md` is left untouched — this is a one-way transform on the
content as it flows toward Notes. Transforms applied (in order):

1. Strip the body's `# AI Research Digest — DATE` H1 — AppleScript adds its own
   title, so the body H1 would just duplicate it.
2. Strip the `_Generated by orchestrator..._` metadata line — visual noise.
2.5. For `trends.md` only — strip the self-documenting meta preamble (status-
   meeting voice, discipline rules, entry format spec, theme inventory)
   between the H1 and the first `---` divider. That preamble is for the
   `ai-trends` agent, not the human reader.
3. Bulletize the major item sections (Major announcements, Research & papers,
   Blog posts, LinkedIn highlights, Jobs). Apple Notes renders bullets with
   visible markers and proper inter-item spacing; standalone `<p>` elements
   stack tightly with no breathing room.
4. Rewrite relative `(../news/...)` cross-references to absolute `file://`
   URLs that actually open in your default markdown viewer when clicked.
5. Convert "Pipeline status" bullets to GFM task-list checkboxes
   (`- [x]` / `- [ ]`) — Notes renders these as real checkboxes.
6. Italicize `Source: [...]` lines for visual de-emphasis and force a paragraph
   break above so they don't merge into the previous item.
7. Append a small italic date footer for search/grep continuity.

Notably NOT applied: `<blockquote>` and `<hr>` — Apple Notes renders both as
essentially invisible (no left bar, no horizontal line), so they add no value.
H2 headings already provide clear visual section separation.

Usage:
    python3 preprocess_digest.py path/to/daily/2026-05-05.md   # writes to stdout
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import quote

WORKSPACE = Path("/Users/yruosch/Documents/Claude/Projects/AI Researcher")


def rel_to_file_url(rel_path: str, base_dir: Path) -> str:
    """Convert a path relative to base_dir into an absolute file:// URL.

    Cadence files now live in nested `{cadence}/{YYYY}/{MM}/` subfolders, so
    relative cross-references like `../../../news/2026/05/2026-05-08.md` from
    inside `daily/2026/05/2026-05-08.md` need to resolve against the SOURCE
    file's directory — not a fixed DAILY_DIR.
    """
    abs_path = (base_dir / rel_path).resolve()
    return f"file://{quote(str(abs_path))}"


def strip_body_h1(text: str) -> str:
    """Remove the body's first H1 line — AppleScript adds its own title wrapper.

    Works for any first-line `# …` heading (daily / weekly / monthly / trends).
    """
    return re.sub(r"\A\s*#\s+[^\n]*\n+", "", text)


def strip_orchestrator_meta(text: str) -> str:
    """Drop the noisy '_Generated by orchestrator..._' italic line."""
    return re.sub(
        r"^_Generated[^_\n]*_\s*\n+",
        "",
        text,
        flags=re.MULTILINE,
    )


def strip_trends_preamble(text: str) -> str:
    """Strip the trends.md meta-documentation block from the Notes rendering.

    The source `trends.md` carries a self-documenting preamble (Status-meeting
    voice, discipline, entry format spec, theme inventory) that's useful for
    `ai-trends` agent invocations but pure noise for the human reader in Notes.
    We strip everything from the start of the document up to and INCLUDING the
    first `\n---\n` divider — which is where the actual monthly sections begin.

    Detected by presence of both meta strings near the top. If absent, no-op
    (so daily / weekly / monthly files pass through untouched).
    """
    head = text[:1500]
    if "Status-meeting view:" not in head or "Themes used so far:" not in head:
        return text
    # Find first standalone `---` divider line and drop everything up to it.
    return re.sub(r"\A.*?\n---\s*\n+", "", text, count=1, flags=re.DOTALL)


def bulletize_item_sections(text: str) -> str:
    """Turn `**Headline** — body…` paragraphs in the major content sections
    into bulleted list items. Apple Notes renders bullets with visible markers
    and noticeable spacing between items, which `<p>` elements lack.

    Sections affected: Major announcements & releases, Research & papers,
    Blog posts & deep dives, LinkedIn highlights, Open AI/LLM/GenAI jobs.
    Source / Note / etc. paragraphs stay as paragraphs.
    """
    target_sections = (
        # daily/
        "Major announcements & releases",
        "Research & papers",
        "Blog posts & deep dives",
        "LinkedIn highlights",
        "Open AI/LLM/GenAI jobs in Switzerland",
        # weekly/
        "Top stories",
        "Top papers",
        "Best blog reads",
        # monthly/
        "Defining themes",
        "Major releases & milestones",
        "Research highlights",
    )

    def transform_body(body: str) -> str:
        paragraphs = re.split(r"\n\s*\n", body.strip())
        out: list[str] = []
        for p in paragraphs:
            p_stripped = p.strip()
            if not p_stripped:
                continue
            # Headline-led item: starts with **bold** and contains an em dash
            # within the first ~200 chars. Bulletize.
            if p_stripped.startswith("**") and " — " in p_stripped[:300]:
                # GFM list item: `- ` then content; multi-line content gets
                # 2-space continuation indent so wrapped lines stay in the bullet
                first, *rest = p_stripped.splitlines()
                lines = [f"- {first}"] + [f"  {l}" for l in rest]
                out.append("\n".join(lines))
            else:
                out.append(p_stripped)
        # Loose list (blank lines between bullets) → pandoc wraps each in <p>,
        # which gives Notes proper inter-item spacing.
        return "\n\n".join(out)

    for name in target_sections:
        pattern = re.compile(
            rf"(##\s*{re.escape(name)}\s*\n)(?P<body>.*?)(?=\n##\s|\Z)",
            flags=re.DOTALL,
        )

        def replace(match: re.Match) -> str:
            return match.group(1) + "\n" + transform_body(match.group("body")) + "\n"

        text = pattern.sub(replace, text)
    return text


def rewrite_relative_links(text: str, base_dir: Path) -> str:
    """[label](../news/x.md) -> [label](file:///abs/path/news/x.md).

    base_dir is the directory of the source markdown file — relative paths
    inside the file resolve against it. Cadence files live at
    `{cadence}/{YYYY}/{MM}/`, so their links use `../../../{cadence}/...`.
    """

    def replace(match: re.Match) -> str:
        label, target = match.group(1), match.group(2)
        return f"[{label}]({rel_to_file_url(target, base_dir)})"

    return re.sub(r"\[([^\]]+)\]\((\.\./[^)]+)\)", replace, text)


def pipeline_to_checklist(text: str) -> str:
    """Replace bullets in '## Pipeline status' with GFM task-list checkboxes."""
    section_re = re.compile(
        r"(##\s*Pipeline status\s*\n)(?P<body>.*?)(?=\n##\s|\Z)",
        flags=re.DOTALL,
    )

    def line_to_checkbox(line: str) -> str:
        m = re.match(r"^(\s*)-\s+(.+)$", line)
        if not m:
            return line
        indent, content = m.group(1), m.group(2)
        # parse "name: status (...)" — checked only if status word == "ok"
        status_match = re.match(r"[^:]+:\s*([A-Za-z]+)", content)
        status = status_match.group(1).lower() if status_match else ""
        mark = "x" if status == "ok" else " "
        return f"{indent}- [{mark}] {content}"

    def replace(match: re.Match) -> str:
        head = match.group(1)
        body = match.group("body")
        new_body = "\n".join(line_to_checkbox(l) for l in body.splitlines())
        return head + new_body

    return section_re.sub(replace, text)


def italicize_source_lines(text: str) -> str:
    """Make 'Source: [label](url)' lines their own paragraph and italicize them.

    Ensures a blank line above each Source: line (so pandoc treats it as its own
    paragraph instead of folding it into the preceding paragraph), then wraps
    the line in `_..._` for visual de-emphasis in Notes.
    """
    # 1. ensure each Source: line is its own paragraph (blank line above)
    text = re.sub(r"(?<!\n)\n(Source:\s+\[)", r"\n\n\1", text)
    # 2. italicize the line — `[ \t]*$` (not `\s*$`) so we don't eat the trailing
    #    newline that separates this paragraph from the next one
    return re.sub(
        r"^(Source:\s+\[[^\]]+\]\([^)]+\))[ \t]*$",
        r"_\1_",
        text,
        flags=re.MULTILINE,
    )


def append_date_footer(text: str, date_str: str) -> str:
    """No-op — kept for backward compatibility. The H1 wrapper added by the
    AppleScript already carries the date/week/month identifier, so a footer
    just adds noise. Drop in callers; left here so importers don't break.
    """
    return text


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: preprocess_digest.py PATH", file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    text = src.read_text()

    date_match = re.search(r"(\d{4}-\d{2}-\d{2})", src.name)
    date_str = date_match.group(1) if date_match else "unknown"

    text = strip_body_h1(text)
    text = strip_orchestrator_meta(text)
    text = strip_trends_preamble(text)
    # italicize_source_lines must run BEFORE bulletize_item_sections so the
    # paragraph break it inserts above each Source: line is in place — otherwise
    # bulletize folds Source: as a continuation of the previous item.
    text = italicize_source_lines(text)
    text = bulletize_item_sections(text)
    text = rewrite_relative_links(text, src.parent)
    text = pipeline_to_checklist(text)
    text = append_date_footer(text, date_str)

    sys.stdout.write(text.lstrip())
    return 0


if __name__ == "__main__":
    sys.exit(main())
